### ISSUE TITLE
[New Blueprint]: OpenJS Architect

### ISSUE THREAD

**Issue by brianleroux** [ran-isenberg/awesome-serverless-blueprints#10]
### Blueprint Name

Architect: local dev hello world SSR with Web Components

### Maintainer

brianleroux

### Maintainer URL

https://github.com/brianleroux

### Repository Link

https://github.com/brianleroux/arc-example-hono-enhance-ssr

### Description

Server-side render Web Components using HonoJS on top of API Gateway and Lambda

### Infrastructure as Code (IaC) Tool

OpenJS Architect (generates AWS SAM)

### CI/CD Tool

Github Actions

### Programming Language

JavaScript

**Comment by ran-isenberg** [comment]
merged in #11
