### ISSUE TITLE
[New Blueprint]: Serverless AWS CDK Pipeline Best Practices & Patterns

### ISSUE THREAD

**Issue by leegilmorecode** [ran-isenberg/awesome-serverless-blueprints#12]
### Blueprint Name

Serverless AWS CDK Pipeline Best Practices & Patterns

### Maintainer

@leegilmorecode

### Maintainer URL

https://www.serverlessadvocate.com/

### Repository Link

https://github.com/leegilmorecode/Serverless-AWS-CDK-Best-Practices-Patterns

### Description

An opinionated AWS CDK solution with full pipeline in-line with the AWS Deployment Pipeline Reference Architecture (DPRA). It covers everything from best practices for setting up an AWS CDK application, progressive deployments with AWS CodeDeploy, to feature flags, performance testing, synthetics, e2e testing and more.

### Infrastructure as Code (IaC) Tool

AWS CDK

### CI/CD Tool

AWS CDK Pipelines

### Programming Language

Typescript

**Comment by ran-isenberg** [comment]
@leegilmorecode  see https://github.com/ran-isenberg/awesome-serverless-blueprints/pull/13
let me know when it's ok to merge
