### ISSUE TITLE
[New Blueprint]: CDK Serverless

### ISSUE THREAD

**Issue by hoegertn** [ran-isenberg/awesome-serverless-blueprints#5]
### Blueprint Name

CDK Serverless

### Maintainer

@hoegertn

### Maintainer URL

https://openconstructfoundation.org/

### Repository Link

https://github.com/open-constructs/cdk-serverless

### Description

CDK Serverless is a powerful toolkit designed to simplify serverless application development using the AWS Cloud Development Kit (CDK).

### Infrastructure as Code (IaC) Tool

AWS CDK

### CI/CD Tool

Up to the user. Recommend projen-pipelines

### Programming Language

TypeScript

**Comment by ran-isenberg** [comment]
implemented in (#6 )
