### ISSUE TITLE
Rust Lambda functions with `cargo-lambda`

### ISSUE THREAD

**Issue by lmammino** [ran-isenberg/awesome-serverless-blueprints#8]
### Blueprint Name

Rust Lambda function

### Maintainer

cargo-lambda

### Maintainer URL

https://www.cargo-lambda.info/

### Repository Link

https://github.com/cargo-lambda/cargo-lambda

### Description

A Cargo extension that allows to easily scaffold new Rust Lambda projects

### Infrastructure as Code (IaC) Tool

None (but SAM, CDK and Terraform can be added easily)

### CI/CD Tool

None, but the repo has some examples with GitHub Actions

### Programming Language

Rust

**Comment by ran-isenberg** [comment]
resolved in https://github.com/ran-isenberg/awesome-serverless-blueprints/pull/9
